package go2linq

import (
	"iter"

	"github.com/solsw/errorhelper"
)

// [InfiniteSequence] generates an infinite sequence that begins with 'start'
// and yields additional values generated by 'next'.
//
// [InfiniteSequence]: https://learn.microsoft.com/dotnet/api/system.linq.enumerable.infinitesequence
func InfiniteSequence[T any](start T, next func(prev T) T) (iter.Seq[T], error) {
	if next == nil {
		return nil, errorhelper.CallerError(ErrNilNext)
	}
	return func(yield func(T) bool) {
			value := start
			for {
				if !yield(value) {
					return
				}
				value = next(value)
			}
		},
		nil
}
